#############################################################################
# Makefile for building: web-snake.js
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  web-snake.pro
# Template: app
# Command: /home/tangarr/opt/Qt/5.15.2/wasm_32/bin/qmake -o Makefile web-snake.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../../opt/Qt/5.15.2/wasm_32/include -I../../opt/Qt/5.15.2/wasm_32/include/QtQuick -I../../opt/Qt/5.15.2/wasm_32/include/QtGui -I../../opt/Qt/5.15.2/wasm_32/include/QtQmlModels -I../../opt/Qt/5.15.2/wasm_32/include/QtQml -I../../opt/Qt/5.15.2/wasm_32/include/QtNetwork -I../../opt/Qt/5.15.2/wasm_32/include/QtCore -I. -I/home/tangarr/.emscripten_ports/openssl/include -I../../opt/Qt/5.15.2/wasm_32/mkspecs/wasm-emscripten
QMAKE         = /home/tangarr/opt/Qt/5.15.2/wasm_32/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/tangarr/opt/Qt/5.15.2/wasm_32/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/tangarr/opt/Qt/5.15.2/wasm_32/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = web-snake.js1.0.0
DISTDIR = /home/tangarr/src/web-snake/.tmp/web-snake.js1.0.0
LINK          = em++
LFLAGS        = -s WASM=1 -s FULL_ES2=1 -s FULL_ES3=1 -s USE_WEBGL2=1 -s EXIT_RUNTIME=1 -s ERROR_ON_UNDEFINED_SYMBOLS=1 -s EXTRA_EXPORTED_RUNTIME_METHODS=["UTF16ToString","stringToUTF16"] --bind -s FETCH=1 -O2 -s ALLOW_MEMORY_GROWTH=1
LIBS          = $(SUBLIBS) /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/platforms/libqwasm.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5EventDispatcherSupport.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5FontDatabaseSupport.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libqtfreetype.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5EglSupport.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqgif.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqicns.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqico.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqjpeg.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqtga.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqtiff.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqwbmp.a /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqwebp.a /home/tangarr/opt/Qt/5.15.2/wasm_32/qml/QtQuick/Window.2/libwindowplugin.a /home/tangarr/opt/Qt/5.15.2/wasm_32/qml/QtQml/libqmlplugin.a /home/tangarr/opt/Qt/5.15.2/wasm_32/qml/QtQml/Models.2/libmodelsplugin.a /home/tangarr/opt/Qt/5.15.2/wasm_32/qml/QtQuick.2/libqtquick2plugin.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Quick.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5QmlModels.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Qml.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Gui.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libqtlibpng.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libqtharfbuzz.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Network.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Core.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libqtpcre2.a   
AR            = emar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp /home/tangarr/src/web-snake/web-snake.js_plugin_import.cpp \
		/home/tangarr/src/web-snake/web-snake.js_qml_plugin_import.cpp \
		qrc_qml.cpp
OBJECTS       = main.o \
		web-snake.js_plugin_import.o \
		web-snake.js_qml_plugin_import.o \
		qrc_qml.o
DIST          = ../../opt/Qt/5.15.2/wasm_32/mkspecs/features/spec_pre.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/common/sanitize.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/common/gcc-base.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/common/clang.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/qdevice.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/device_config.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/emcc_ver.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/qconfig.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_core.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_network.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt_functions.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt_config.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/exclusive_builds.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/toolchain.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/default_pre.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/default_pre.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resolve_config.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/default_post.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/wasm.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/warn_on.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resources_functions.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resources.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/moc.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/unix/opengl.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qmake_use.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/file_copies.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/testcase_targets.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/exceptions.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/yacc.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/lex.prf \
		web-snake.pro  main.cpp
QMAKE_TARGET  = web-snake.js
DESTDIR       = 
TARGET        = web-snake.js


first: all
####### Build rules

web-snake.js: /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Quick.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Gui.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5QmlModels.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Qml.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Network.a /home/tangarr/opt/Qt/5.15.2/wasm_32/lib/libQt5Core.a $(OBJECTS)  apphtml appjs appsvg
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: web-snake.pro ../../opt/Qt/5.15.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf ../../opt/Qt/5.15.2/wasm_32/mkspecs/features/spec_pre.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/common/sanitize.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/common/gcc-base.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/common/clang.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/qdevice.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/device_config.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/emcc_ver.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/qconfig.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_core.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_network.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt_functions.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt_config.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/exclusive_builds.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/toolchain.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/default_pre.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/default_pre.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resolve_config.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/default_post.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/wasm.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/warn_on.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resources_functions.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resources.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/moc.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/unix/opengl.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qmake_use.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/file_copies.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/testcase_targets.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/exceptions.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/yacc.prf \
		../../opt/Qt/5.15.2/wasm_32/mkspecs/features/lex.prf \
		web-snake.pro \
		qml.qrc \
		../../opt/Qt/5.15.2/wasm_32/plugins/platforms/libqwasm.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqgif.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqicns.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqico.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqjpeg.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqtga.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqtiff.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqwbmp.prl \
		../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqwebp.prl \
		../../opt/Qt/5.15.2/wasm_32/lib/libQt5Quick.prl \
		../../opt/Qt/5.15.2/wasm_32/lib/libQt5Gui.prl \
		../../opt/Qt/5.15.2/wasm_32/lib/libQt5QmlModels.prl \
		../../opt/Qt/5.15.2/wasm_32/lib/libQt5Qml.prl \
		../../opt/Qt/5.15.2/wasm_32/lib/libQt5Network.prl \
		../../opt/Qt/5.15.2/wasm_32/lib/libQt5Core.prl \
		../../opt/Qt/5.15.2/wasm_32/qml/QtQuick.2/libqtquick2plugin.prl \
		../../opt/Qt/5.15.2/wasm_32/qml/QtQuick/Window.2/libwindowplugin.prl \
		../../opt/Qt/5.15.2/wasm_32/qml/QtQml/libqmlplugin.prl \
		../../opt/Qt/5.15.2/wasm_32/qml/QtQml/Models.2/libmodelsplugin.prl
	$(QMAKE) -o Makefile web-snake.pro
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/spec_pre.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/common/sanitize.conf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/common/gcc-base.conf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/common/clang.conf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/qdevice.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/device_config.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/emcc_ver.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/qconfig.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_core.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_core_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gamepad.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gui.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_gui_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimedia.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_network.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_network_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_opengl.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_printsupport.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qml.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qml_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmltest.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quick.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quick_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_repparser.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_scxml.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_sensors.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_svg.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_svg_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_testlib.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uitools.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webchannel.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_websockets.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webview.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_webview_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_widgets.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xml.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xml_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qgif.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qicns.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qico.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtga.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt_functions.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt_config.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/wasm-emscripten/qmake.conf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/spec_post.prf:
.qmake.stash:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/exclusive_builds.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/toolchain.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/default_pre.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/default_pre.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resolve_config.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/default_post.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/wasm/wasm.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/warn_on.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qt.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resources_functions.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/resources.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/moc.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/unix/opengl.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/qmake_use.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/file_copies.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/testcase_targets.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/exceptions.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/yacc.prf:
../../opt/Qt/5.15.2/wasm_32/mkspecs/features/lex.prf:
web-snake.pro:
qml.qrc:
../../opt/Qt/5.15.2/wasm_32/plugins/platforms/libqwasm.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqgif.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqicns.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqico.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqjpeg.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqtga.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqtiff.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqwbmp.prl:
../../opt/Qt/5.15.2/wasm_32/plugins/imageformats/libqwebp.prl:
../../opt/Qt/5.15.2/wasm_32/lib/libQt5Quick.prl:
../../opt/Qt/5.15.2/wasm_32/lib/libQt5Gui.prl:
../../opt/Qt/5.15.2/wasm_32/lib/libQt5QmlModels.prl:
../../opt/Qt/5.15.2/wasm_32/lib/libQt5Qml.prl:
../../opt/Qt/5.15.2/wasm_32/lib/libQt5Network.prl:
../../opt/Qt/5.15.2/wasm_32/lib/libQt5Core.prl:
../../opt/Qt/5.15.2/wasm_32/qml/QtQuick.2/libqtquick2plugin.prl:
../../opt/Qt/5.15.2/wasm_32/qml/QtQuick/Window.2/libwindowplugin.prl:
../../opt/Qt/5.15.2/wasm_32/qml/QtQml/libqmlplugin.prl:
../../opt/Qt/5.15.2/wasm_32/qml/QtQml/Models.2/libmodelsplugin.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile web-snake.pro

qmake_all: FORCE


all: Makefile web-snake.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../opt/Qt/5.15.2/wasm_32/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm /home/tangarr/src/web-snake/web-snake.js_plugin_import.cpp /home/tangarr/src/web-snake/web-snake.js_qml_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/platforms/wasm_shell.html
	sed -e s/@APPNAME@/web-snake/g /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/platforms/wasm_shell.html > /home/tangarr/src/web-snake/web-snake.html

appjs: /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/platforms/qtloader.js
	cp -f /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/platforms/qtloader.js /home/tangarr/src/web-snake

appsvg: /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/platforms/qtlogo.svg
	cp -f /home/tangarr/opt/Qt/5.15.2/wasm_32/plugins/platforms/qtlogo.svg /home/tangarr/src/web-snake

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) web-snake.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../opt/Qt/5.15.2/wasm_32/bin/rcc \
		Snake.qml \
		SnakeSegment.qml \
		main.qml
	/home/tangarr/opt/Qt/5.15.2/wasm_32/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../opt/Qt/5.15.2/wasm_32/mkspecs/features/data/dummy.cpp
	em++ -pipe -O2 -std=gnu++11 -s ALLOW_MEMORY_GROWTH=1 -Wall -Wextra -dM -E -o moc_predefs.h ../../opt/Qt/5.15.2/wasm_32/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp ../../opt/Qt/5.15.2/wasm_32/include/QtGui/QGuiApplication \
		../../opt/Qt/5.15.2/wasm_32/include/QtGui/qguiapplication.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtGui/qtguiglobal.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qglobal.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qconfig-bootstrapped.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qconfig.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qtcore-config.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qsystemdetection.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qprocessordetection.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qcompilerdetection.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qtypeinfo.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qsysinfo.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qlogging.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qflags.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qatomic.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qbasicatomic.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qatomic_bootstrap.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qgenericatomic.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qatomic_cxx11.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qatomic_msvc.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qglobalstatic.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qmutex.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qnumeric.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qversiontagging.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtGui/qtgui-config.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qcoreapplication.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qstring.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qchar.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qbytearray.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qrefcount.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qnamespace.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qarraydata.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qstringliteral.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qstringalgorithms.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qstringview.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qstringbuilder.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qobject.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qobjectdefs.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qobjectdefs_impl.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qlist.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qalgorithms.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qiterator.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qhashfunctions.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qpair.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qvector.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qcontainertools_impl.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qpoint.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qbytearraylist.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qstringlist.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qregexp.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qstringmatcher.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qcoreevent.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qscopedpointer.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qmetatype.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qvarlengtharray.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qcontainerfwd.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qobject_impl.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qeventloop.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtGui/qwindowdefs.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtGui/qwindowdefs_win.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtGui/qinputmethod.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qlocale.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qvariant.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qmap.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qdebug.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qhash.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qtextstream.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qiodevice.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qset.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qcontiguouscache.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qsharedpointer.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qshareddata.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qsharedpointer_impl.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qsize.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qmargins.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/QQmlApplicationEngine \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmlapplicationengine.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmlengine.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qurl.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qurlquery.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qjsengine.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qjsvalue.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qtqmlglobal.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qtqml-config.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtNetwork/qtnetworkglobal.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtNetwork/qtnetwork-config.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmldebug.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqml.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmlprivate.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmlparserstatus.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmllist.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmlpropertyvaluesource.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qpointer.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtCore/qmetaobject.h \
		../../opt/Qt/5.15.2/wasm_32/include/QtQml/qqmlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

web-snake.js_plugin_import.o: /home/tangarr/src/web-snake/web-snake.js_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o web-snake.js_plugin_import.o /home/tangarr/src/web-snake/web-snake.js_plugin_import.cpp

web-snake.js_qml_plugin_import.o: /home/tangarr/src/web-snake/web-snake.js_qml_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o web-snake.js_qml_plugin_import.o /home/tangarr/src/web-snake/web-snake.js_qml_plugin_import.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/web-snake/bin || mkdir -p $(INSTALL_ROOT)/opt/web-snake/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/web-snake/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/web-snake/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/web-snake/bin/ 


install_js_file: first FORCE
	@test -d $(INSTALL_ROOT)/opt/web-snake/bin || mkdir -p $(INSTALL_ROOT)/opt/web-snake/bin
	$(QINSTALL_PROGRAM) /home/tangarr/src/web-snake/web-snake.js $(INSTALL_ROOT)/opt/web-snake/bin/web-snake.js

uninstall_js_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/web-snake/bin/web-snake.js
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/web-snake/bin/ 


install: install_target install_js_file  FORCE

uninstall: uninstall_target uninstall_js_file  FORCE

FORCE:

